trigger: none

pool:

stages:
  - stage: 
    jobs:
      - job: 
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '16'

          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'sudo npm install'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'sudo npm run build'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Pipeline.Workspace)'
              publishLocation: 'pipeline'

