trigger: none

pool: Himalay

stages:
  - stage: CI
    jobs:
      - job: 
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '16'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'npm install'
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: 'npn run build'

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(Build.ArtifactStagingDirectory)/build'
              publishLocation: 'pipeline'

