trigger: none

pool: Himalay

stages:
  - stage: CI
    jobs:
      - job: 
        steps:
          - task: NodeTaskRunnerInstaller@0
            inputs:
              nodeVersion: '16'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'npm install'
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: 'npm run build'
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/build'
              artifact: 'drop'
              publishLocation: 'pipeline'
  - stage: CD
    jobs:
      - job: 
        steps:
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'current'
              artifactName: 'drop'
              targetPath: '$(System.DefaultWorkingDirectory)/build'
          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: 'ssh'
              sourceFolder: '$(System.DefaultWorkingDirectory)/build'
              contents: '**'
              targetFolder: '/home/username/artifact'
              readyTimeout: '20000'
          - task: SSH@0
            inputs:
              sshEndpoint: 'ssh'
              runOptions: 'commands'
              commands: 'sudo apt install nginx'
              readyTimeout: '20000'

          
          
  
